name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore YourSolution.sln

    - name: Build solution
      run: dotnet build YourSolution.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test YourSolution.sln --no-build --verbosity normal